# GitHub Labels Configuration
# Apply with: gh label import .github/labels.yml

- name: bug
  color: d73a4a
  description: Something isn't working

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: good first issue
  color: 7057ff
  description: Good for newcomers

- name: help wanted
  color: 008672
  description: Extra attention is needed

- name: mcp-server
  color: 1d76db
  description: MCP Server component

- name: nextcloud-app
  color: 5319e7
  description: Nextcloud App component

- name: phase-2
  color: fbca04
  description: Roadmap Phase 2

- name: phase-3
  color: f9d0c4
  description: Roadmap Phase 3

- name: phase-4
  color: c5def5
  description: Roadmap Phase 4

- name: wontfix
  color: ffffff
  description: This will not be worked on
