package config

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"
)

// Env holds all variables needed to generate the .env file on the remote server.
type Env struct {
	NextcloudURL      string
	NextcloudUser     string
	NextcloudPassword string
	Domain            string
	AuthSecret        string
	ClientSecret      string
	// Pre-filled static values
	AuthIssuer          string
	ClientID            string
	RegistrationEnabled bool
	RegistrationToken   string
	// CrowdSec + TLS
	CrowdSecBouncerKey string
	AcmeEmail          string
	// Monitoring (Grafana)
	GrafanaPassword string
}

// Generate builds the .env file content with random secrets.
func Generate(ncURL, ncUser, ncPassword, domain, acmeEmail string) (*Env, error) {
	authSecret, err := randomHex(32)
	if err != nil {
		return nil, fmt.Errorf("generate auth secret: %w", err)
	}
	clientSecret, err := randomHex(32)
	if err != nil {
		return nil, fmt.Errorf("generate client secret: %w", err)
	}
	regToken, err := randomHex(16)
	if err != nil {
		return nil, fmt.Errorf("generate registration token: %w", err)
	}
	bouncerKey, err := randomHex(32)
	if err != nil {
		return nil, fmt.Errorf("generate crowdsec bouncer key: %w", err)
	}
	grafanaPassword, err := randomHex(16)
	if err != nil {
		return nil, fmt.Errorf("generate grafana password: %w", err)
	}

	return &Env{
		NextcloudURL:        ncURL,
		NextcloudUser:       ncUser,
		NextcloudPassword:   ncPassword,
		Domain:              domain,
		AuthSecret:          authSecret,
		ClientSecret:        clientSecret,
		AuthIssuer:          "https://" + domain,
		ClientID:            "aiquila-claude",
		RegistrationEnabled: true,
		RegistrationToken:   regToken,
		CrowdSecBouncerKey:  bouncerKey,
		AcmeEmail:           acmeEmail,
		GrafanaPassword:     grafanaPassword,
	}, nil
}

// Render returns the contents of the .env file as a string.
func (e *Env) Render() string {
	var b strings.Builder
	b.WriteString("# AIquila MCP Server — generated by aiquila-hetzner\n\n")

	b.WriteString("# Nextcloud connection\n")
	b.WriteString(fmt.Sprintf("NEXTCLOUD_URL=%s\n", e.NextcloudURL))
	b.WriteString(fmt.Sprintf("NEXTCLOUD_USER=%s\n", e.NextcloudUser))
	b.WriteString(fmt.Sprintf("NEXTCLOUD_PASSWORD=%s\n", e.NextcloudPassword))
	b.WriteString("\n")

	b.WriteString("# MCP transport\n")
	b.WriteString("MCP_TRANSPORT=http\n")
	b.WriteString("MCP_PORT=3339\n")
	b.WriteString("\n")

	b.WriteString("# OAuth 2.0\n")
	b.WriteString("MCP_AUTH_ENABLED=true\n")
	b.WriteString(fmt.Sprintf("MCP_AUTH_SECRET=%s\n", e.AuthSecret))
	b.WriteString(fmt.Sprintf("MCP_AUTH_ISSUER=%s\n", e.AuthIssuer))
	b.WriteString(fmt.Sprintf("MCP_CLIENT_ID=%s\n", e.ClientID))
	b.WriteString(fmt.Sprintf("MCP_CLIENT_SECRET=%s\n", e.ClientSecret))
	b.WriteString(fmt.Sprintf("MCP_REGISTRATION_ENABLED=%v\n", e.RegistrationEnabled))
	b.WriteString(fmt.Sprintf("MCP_REGISTRATION_TOKEN=%s\n", e.RegistrationToken))
	b.WriteString("MCP_TRUST_PROXY=true\n")
	b.WriteString("\n")

	b.WriteString("# Traefik / TLS\n")
	b.WriteString(fmt.Sprintf("MCP_DOMAIN=%s\n", e.Domain))
	b.WriteString(fmt.Sprintf("ACME_EMAIL=%s\n", e.AcmeEmail))
	b.WriteString("\n")

	b.WriteString("# CrowdSec\n")
	b.WriteString(fmt.Sprintf("CROWDSEC_BOUNCER_KEY=%s\n", e.CrowdSecBouncerKey))
	b.WriteString("\n")

	b.WriteString("# Monitoring (Grafana)\n")
	b.WriteString(fmt.Sprintf("GRAFANA_PASSWORD=%s\n", e.GrafanaPassword))
	b.WriteString("\n")

	b.WriteString("# Logging\n")
	b.WriteString("LOG_LEVEL=info\n")

	return b.String()
}

func randomHex(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}
